"""
File: app/models/user.py
Purpose: SQLAlchemy ORM model for application users.

What this file does:
- Defines the `users` table shape
- Maps table columns to Python attributes on the User class
"""

from sqlalchemy import Column, Integer, String, DateTime, func
from app.core.db import Base


class User(Base):
    # Name of the table in the database.
    __tablename__ = "users"

    # Primary key for each user row.
    id = Column(Integer, primary_key=True, index=True)

    # Unique email used for login/identity.
    email = Column(String, unique=True, index=True, nullable=False)

    # Optional display name.
    full_name = Column(String, nullable=True)

    # Securely hashed password, never the plain password.
    hashed_password = Column(String, nullable=False)

    # Timestamp automatically generated by the database.
    created_at = Column(DateTime(timezone=True), server_default=func.now())
